# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Apply to nv-oem-config-debconf@ttyGS0.service only, not nv-oobe.service.
[Unit]
Conflicts=serial-getty@ttyGS0.service
After=serial-getty@ttyGS0.service
